### ISSUE TITLE
Commands added with an object don't get disposed

### ISSUE THREAD

**Issue by olmokramer** [mark-hahn/sub-atom#1]
Take the following example package:

``` json
// package.json
{
  "name": "test-package",
  "main": "lib/main",
  "dependencies": {
    "sub-atom": "0.1.3"
  }
}
```

``` coffee
# lib/main.coffee
'use strict'
{CompositeDisposable} = require 'atom'
SubAtom = require 'sub-atom'

class TestPackage
  activate: ->
    # CompositeDisposable, commands 1, 2 and 3
    @subs = new CompositeDisposable()
    @subs.add atom.commands.add 'atom-workspace',
      'test-package:test-command-1': -> console.log 'test-1'
      'test-package:test-command-2': -> console.log 'test-2'
    @subs.add atom.commands.add 'atom-workspace', 'test-package:test-command-3', -> console.log 'test-3'

    # SubAtom, commands 4, 5 and 6
    @subs2 = new SubAtom()
    @subs2.add atom.commands.add 'atom-workspace', 'test-package:test-command-4', -> console.log 'test-4'
    @subs2.add atom.commands.add 'atom-workspace',
      'test-package:test-command-5': -> console.log 'test-5'
      'test-package:test-command-6': -> console.log 'test-6'

    # CommandRegistry, commands 7, 8, and 9
    @subSingleCommand = atom.commands.add 'atom-workspace', 'test-package:test-command-7', -> console.log 'test-7'
    @subMultipleCommands = atom.commands.add 'atom-workspace',
      'test-package:test-command-8': -> console.log 'test-8'
      'test-package:test-command-9': -> console.log 'test-9'

  deactivate: ->
    @subs.dispose()
    @subs2.dispose()
    @subSingleCommand.dispose()
    @subMultipleCommands.dispose()

module.exports = new TestPackage()
```

When the package is enabled, `test-package:test-command-[1 through 9]` commands will be available. When the package is disabled from within the settings view, commands `test-package:test-command-[5 or 6]` (the ones registered with an object) will still be available from the command palette, the other ones are gone. Then when the package is enabled again from the settings view, all commands are available again, but when I trigger `test-package:test-command-[5 or 6]`, the registered handler function will be called <em>twice</em>. After another routine of disabling/enabling the handlers will be called three times etc.

Atom 0.179.0
Linux Debian 8

**Comment by olmokramer** [comment]
This is also true for DOM event handlers added

**Comment by olmokramer** [comment]
Accidentally clicked close...

**Comment by mark-hahn** [comment]
Thanks very much for the detailed report.  I hope you didn't write all that code for this report.  That has more code than this package. (grin)

Time to dive into core ...

**Comment by mark-hahn** [comment]
I couldn't repeat this on 179 and windows 8.1.  I used your exact files and repeat steps.

However, I made an educated guess and put up a new version 0.1.4 on npm. Can you please try it?

**Comment by olmokramer** [comment]
Thanks! I'll try it tonight

**Comment by olmokramer** [comment]
Never mind, I had to know right now (grin). New version seems to work fine! Thanks for the quick fix

**Comment by mark-hahn** [comment]
Thanks mucho.
